openapi: 3.0.0
info:
  title: API de Rastreamento de Veículos
  description: Documentação da API de Rastreamento de Veículos
  version: 1.0.0
paths:
  /:
    get:
      summary: Retorna todos os usuários cadastrados
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ID do usuário
                        nome:
                          type: string
                          description: Nome do usuário
                        email:
                          type: string
                          format: email
                          description: Email do usuário
                        telefone:
                          type: string
                          description: Telefone do usuário
                        endereco:
                          type: string
                          description: Endereço do usuário
                        data_nascimento:
                          type: string
                          format: date
                          description: Data de nascimento do usuário
